2025-05-06 14:19:04,089 INFO    MainThread:37270 [wandb_setup.py:_flush():68] Current SDK version is 0.19.10
2025-05-06 14:19:04,089 INFO    MainThread:37270 [wandb_setup.py:_flush():68] Configure stats pid to 37270
2025-05-06 14:19:04,089 INFO    MainThread:37270 [wandb_setup.py:_flush():68] Loading settings from /home/veit/.config/wandb/settings
2025-05-06 14:19:04,089 INFO    MainThread:37270 [wandb_setup.py:_flush():68] Loading settings from /home/veit/Uni/Lausanne/NML/EPFL-NWML-25/outputs/2025-05-06/14-19-03/wandb/settings
2025-05-06 14:19:04,090 INFO    MainThread:37270 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-05-06 14:19:04,090 INFO    MainThread:37270 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /home/veit/Uni/Lausanne/NML/EPFL-NWML-25/outputs/2025-05-06/14-19-03/wandb/run-20250506_141904-5l6iahzk/logs/debug.log
2025-05-06 14:19:04,090 INFO    MainThread:37270 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /home/veit/Uni/Lausanne/NML/EPFL-NWML-25/outputs/2025-05-06/14-19-03/wandb/run-20250506_141904-5l6iahzk/logs/debug-internal.log
2025-05-06 14:19:04,090 INFO    MainThread:37270 [wandb_init.py:init():852] calling init triggers
2025-05-06 14:19:04,090 INFO    MainThread:37270 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'preprocessing': {'steps': [{'_target_': 'fft_filter', 'filter_order': 4, 'low_freq': 0.5, 'high_freq': 30, 'fs': 250}, {'_target_': 'identity'}]}, 'model': {'hidden_channels': 64, 'num_layers': 3, 'dropout': 0.2}, 'optimizer': {'name': 'Adam'}, 'batch_size': 128, 'num_epochs': 4, 'seed': 42, 'learning_rate': 0.001, 'prefetch_dataset': False, 'data_path': '/home/veit/Uni/Lausanne/NML/EPFL-NWML-25/content/networkML', 'train_set': 'train/train', 'test_set': 'test/test', 'distances_set': 'distances_3d.csv', '_wandb': {}}
2025-05-06 14:19:04,090 INFO    MainThread:37270 [wandb_init.py:init():893] starting backend
2025-05-06 14:19:04,090 INFO    MainThread:37270 [wandb_init.py:init():897] sending inform_init request
2025-05-06 14:19:04,098 INFO    MainThread:37270 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-06 14:19:04,098 INFO    MainThread:37270 [wandb_init.py:init():907] backend started and connected
2025-05-06 14:19:04,102 INFO    MainThread:37270 [wandb_init.py:init():1002] updated telemetry
2025-05-06 14:19:04,114 INFO    MainThread:37270 [wandb_init.py:init():1026] communicating run to backend with 90.0 second timeout
2025-05-06 14:19:04,832 INFO    MainThread:37270 [wandb_init.py:init():1101] starting run threads in backend
2025-05-06 14:19:04,992 INFO    MainThread:37270 [wandb_run.py:_console_start():2566] atexit reg
2025-05-06 14:19:04,992 INFO    MainThread:37270 [wandb_run.py:_redirect():2414] redirect: wrap_raw
2025-05-06 14:19:04,992 INFO    MainThread:37270 [wandb_run.py:_redirect():2483] Wrapping output streams.
2025-05-06 14:19:04,992 INFO    MainThread:37270 [wandb_run.py:_redirect():2506] Redirects installed.
2025-05-06 14:19:04,996 INFO    MainThread:37270 [wandb_init.py:init():1147] run started, returning control to user process
2025-05-06 14:19:05,056 INFO    MainThread:37270 [wandb_run.py:_config_callback():1429] config_cb None None {'cfg': "{'preprocessing': {'steps': [{'_target_': 'fft_filter', 'filter_order': 4, 'low_freq': 0.5, 'high_freq': 30, 'fs': 250}, {'_target_': 'identity'}]}, 'model': {'hidden_channels': 64, 'num_layers': 3, 'dropout': 0.2}, 'optimizer': {'name': 'Adam'}, 'batch_size': 128, 'num_epochs': 4, 'seed': 42, 'learning_rate': 0.001, 'prefetch_dataset': False, 'data_path': '/home/veit/Uni/Lausanne/NML/EPFL-NWML-25/content/networkML', 'train_set': 'train/train', 'test_set': 'test/test', 'distances_set': 'distances_3d.csv'}"}
2025-05-06 14:19:12,267 INFO    MsgRouterThr:37270 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-05-06 14:19:14,631 ERROR   MainThread:37270 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2487, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-06 14:19:14,640 ERROR   MainThread:37270 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2487, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/veit/miniconda3/envs/nml_project/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
